version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: ./server.dockerfile
    env_file: ./configs/server.env
    depends_on:
      - mysql
    image: server-sample-img
    container_name: hack-ios-server
    ports:
      - 8080:8080
    volumes:
      - .:/hack-ios-server
    tty: true

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: "hack-ios-server"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: "hack-ios-server"
    links:
      - mysql
    ports:
      - 4000:80

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    environment:
      SWAGGER_JSON: /api/api-document.yml
    volumes:
      - ./api-document.yml:/api/api-document.yml:ro
    ports:
      - 3000:8080
volumes:
  db-data:
    driver: local
